// Code generated by protoc-gen-go. DO NOT EDIT.
// source: define.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	define.proto
	game_msg.proto
	framework_msg.proto

It has these top-level messages:
	LoginReq
	LoginRespon
	ConnectToGateReq
	ConnectToGateRespon
	RoleInfo
	RoleListReq
	RoleListRespon
	CreateRoleReq
	CreateRoleRespon
	EnterGameReq
	EnterGameRespon
	LeaveGameReq
	LeaveGameRespon
	CreateRoomReq
	CreateRoomRespon
	NodeRegister
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// couple msg start at 1; odd:Req, even:Respon
// single msg start at 10000
type EGameMsgID int32

const (
	EGameMsgID_EGMI_UNKNOW EGameMsgID = 0
	// couple msg start
	EGameMsgID_EGMI_LOGIN_REQ              EGameMsgID = 1
	EGameMsgID_EGMI_LOGIN_RESPON           EGameMsgID = 2
	EGameMsgID_EGMI_CONNECT_TO_GATE_REQ    EGameMsgID = 3
	EGameMsgID_EGMI_CONNECT_TO_GATE_RESPON EGameMsgID = 4
	// single msg start
	EGameMsgID_EGMI_SINGLE_MSG_START EGameMsgID = 10000
)

var EGameMsgID_name = map[int32]string{
	0:     "EGMI_UNKNOW",
	1:     "EGMI_LOGIN_REQ",
	2:     "EGMI_LOGIN_RESPON",
	3:     "EGMI_CONNECT_TO_GATE_REQ",
	4:     "EGMI_CONNECT_TO_GATE_RESPON",
	10000: "EGMI_SINGLE_MSG_START",
}
var EGameMsgID_value = map[string]int32{
	"EGMI_UNKNOW":                 0,
	"EGMI_LOGIN_REQ":              1,
	"EGMI_LOGIN_RESPON":           2,
	"EGMI_CONNECT_TO_GATE_REQ":    3,
	"EGMI_CONNECT_TO_GATE_RESPON": 4,
	"EGMI_SINGLE_MSG_START":       10000,
}

func (x EGameMsgID) String() string {
	return proto.EnumName(EGameMsgID_name, int32(x))
}
func (EGameMsgID) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NODE_TYPE int32

const (
	NODE_TYPE_MACHINE NODE_TYPE = 0
	NODE_TYPE_CENTER  NODE_TYPE = 1
	NODE_TYPE_LOGIN   NODE_TYPE = 2
	NODE_TYPE_GATE    NODE_TYPE = 3
	NODE_TYPE_GAME    NODE_TYPE = 4
	NODE_TYPE_CLIENT  NODE_TYPE = 5
)

var NODE_TYPE_name = map[int32]string{
	0: "MACHINE",
	1: "CENTER",
	2: "LOGIN",
	3: "GATE",
	4: "GAME",
	5: "CLIENT",
}
var NODE_TYPE_value = map[string]int32{
	"MACHINE": 0,
	"CENTER":  1,
	"LOGIN":   2,
	"GATE":    3,
	"GAME":    4,
	"CLIENT":  5,
}

func (x NODE_TYPE) String() string {
	return proto.EnumName(NODE_TYPE_name, int32(x))
}
func (NODE_TYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type NODE_STATU int32

const (
	NODE_STATU_NOT_READY NODE_STATU = 0
	NODE_STATU_READY     NODE_STATU = 1
	NODE_STATU_OFF_LINE  NODE_STATU = 2
)

var NODE_STATU_name = map[int32]string{
	0: "NOT_READY",
	1: "READY",
	2: "OFF_LINE",
}
var NODE_STATU_value = map[string]int32{
	"NOT_READY": 0,
	"READY":     1,
	"OFF_LINE":  2,
}

func (x NODE_STATU) String() string {
	return proto.EnumName(NODE_STATU_name, int32(x))
}
func (NODE_STATU) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterEnum("pb.EGameMsgID", EGameMsgID_name, EGameMsgID_value)
	proto.RegisterEnum("pb.NODE_TYPE", NODE_TYPE_name, NODE_TYPE_value)
	proto.RegisterEnum("pb.NODE_STATU", NODE_STATU_name, NODE_STATU_value)
}

func init() { proto.RegisterFile("define.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4e, 0xc3, 0x40,
	0x0c, 0x45, 0x93, 0x34, 0x2d, 0xad, 0x5b, 0xc0, 0x58, 0xaa, 0x84, 0x00, 0x89, 0x7d, 0x16, 0x6c,
	0xe0, 0x02, 0x51, 0xe2, 0x0e, 0x23, 0x12, 0x4f, 0x49, 0x5c, 0xa1, 0xae, 0x46, 0x54, 0x04, 0xc4,
	0x02, 0x5a, 0x01, 0x07, 0xe1, 0x0e, 0x5c, 0x14, 0x65, 0xba, 0x62, 0xc1, 0xee, 0xeb, 0xfb, 0xff,
	0x67, 0xcb, 0x30, 0x7b, 0xea, 0x9e, 0x5f, 0xdf, 0xbb, 0xab, 0xdd, 0xc7, 0xf6, 0x6b, 0x4b, 0xc9,
	0x6e, 0x93, 0xfd, 0xc4, 0x00, 0x6c, 0x1e, 0xdf, 0xba, 0xfa, 0xf3, 0xc5, 0x96, 0x74, 0x0c, 0x53,
	0x36, 0xb5, 0xf5, 0x2b, 0xb9, 0x13, 0xf7, 0x80, 0x11, 0x11, 0x1c, 0x05, 0xa3, 0x72, 0xc6, 0x8a,
	0x6f, 0xf8, 0x1e, 0x63, 0x9a, 0xc3, 0xc9, 0x1f, 0xaf, 0x5d, 0x3a, 0xc1, 0x84, 0x2e, 0xe0, 0x34,
	0xd8, 0x85, 0x13, 0xe1, 0x42, 0xbd, 0x3a, 0x6f, 0x72, 0xe5, 0x50, 0x1a, 0xd0, 0x25, 0x9c, 0xff,
	0x33, 0x0d, 0xf5, 0x94, 0xce, 0x60, 0x1e, 0x02, 0xad, 0x15, 0x53, 0xb1, 0xaf, 0x5b, 0xe3, 0x5b,
	0xcd, 0x1b, 0xc5, 0x6f, 0xc9, 0x1c, 0x4c, 0xc4, 0x95, 0xec, 0x75, 0xbd, 0x64, 0x9a, 0xc2, 0x41,
	0x9d, 0x17, 0xb7, 0x56, 0x18, 0x23, 0x02, 0x18, 0x15, 0x2c, 0xca, 0x0d, 0xc6, 0x34, 0x81, 0x61,
	0x38, 0x09, 0x13, 0x1a, 0x43, 0xda, 0xd3, 0x71, 0xb0, 0x57, 0x35, 0x63, 0x1a, 0xa2, 0x95, 0x65,
	0x51, 0x1c, 0x66, 0x37, 0x00, 0x01, 0xd8, 0x6a, 0xae, 0x2b, 0x3a, 0xec, 0xf1, 0xea, 0x1b, 0xce,
	0xcb, 0x35, 0x46, 0x3d, 0x67, 0x2f, 0x63, 0x9a, 0xc1, 0xd8, 0x2d, 0x16, 0xbe, 0xea, 0x97, 0x25,
	0x9b, 0x51, 0xf8, 0xdb, 0xf5, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xa0, 0x44, 0x2b, 0x47,
	0x01, 0x00, 0x00,
}
