// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MsgDefine.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// login
type LoginResponCode int32

const (
	LoginResponCode_LOGIN_SUCCESS LoginResponCode = 0
	LoginResponCode_LOGIN_FAIL    LoginResponCode = 1
)

var LoginResponCode_name = map[int32]string{
	0: "LOGIN_SUCCESS",
	1: "LOGIN_FAIL",
}
var LoginResponCode_value = map[string]int32{
	"LOGIN_SUCCESS": 0,
	"LOGIN_FAIL":    1,
}

func (x LoginResponCode) String() string {
	return proto.EnumName(LoginResponCode_name, int32(x))
}
func (LoginResponCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// connect to gate
type ConnectToGateResponCode int32

const (
	ConnectToGateResponCode_CONNECT_TO_GATE_SUCCESS ConnectToGateResponCode = 0
	ConnectToGateResponCode_CONNECT_TO_GATE_FAIL    ConnectToGateResponCode = 1
)

var ConnectToGateResponCode_name = map[int32]string{
	0: "CONNECT_TO_GATE_SUCCESS",
	1: "CONNECT_TO_GATE_FAIL",
}
var ConnectToGateResponCode_value = map[string]int32{
	"CONNECT_TO_GATE_SUCCESS": 0,
	"CONNECT_TO_GATE_FAIL":    1,
}

func (x ConnectToGateResponCode) String() string {
	return proto.EnumName(ConnectToGateResponCode_name, int32(x))
}
func (ConnectToGateResponCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

// create role
type CreateRoleResponCode int32

const (
	CreateRoleResponCode_CREATE_ROLE_SUCCESS CreateRoleResponCode = 0
	CreateRoleResponCode_CREATE_ROLE_FAIL    CreateRoleResponCode = 1
)

var CreateRoleResponCode_name = map[int32]string{
	0: "CREATE_ROLE_SUCCESS",
	1: "CREATE_ROLE_FAIL",
}
var CreateRoleResponCode_value = map[string]int32{
	"CREATE_ROLE_SUCCESS": 0,
	"CREATE_ROLE_FAIL":    1,
}

func (x CreateRoleResponCode) String() string {
	return proto.EnumName(CreateRoleResponCode_name, int32(x))
}
func (CreateRoleResponCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

// enter game
type EnterGameResponCode int32

const (
	EnterGameResponCode_ENTER_GAME_SUCCESS EnterGameResponCode = 0
	EnterGameResponCode_ENTER_GAME_FAIL    EnterGameResponCode = 1
)

var EnterGameResponCode_name = map[int32]string{
	0: "ENTER_GAME_SUCCESS",
	1: "ENTER_GAME_FAIL",
}
var EnterGameResponCode_value = map[string]int32{
	"ENTER_GAME_SUCCESS": 0,
	"ENTER_GAME_FAIL":    1,
}

func (x EnterGameResponCode) String() string {
	return proto.EnumName(EnterGameResponCode_name, int32(x))
}
func (EnterGameResponCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

// leave game
type LeaveGameResponCode int32

const (
	LeaveGameResponCode_LEAVE_GAME_SUCCESS LeaveGameResponCode = 0
	LeaveGameResponCode_LEAVE_GAME_FAIL    LeaveGameResponCode = 1
)

var LeaveGameResponCode_name = map[int32]string{
	0: "LEAVE_GAME_SUCCESS",
	1: "LEAVE_GAME_FAIL",
}
var LeaveGameResponCode_value = map[string]int32{
	"LEAVE_GAME_SUCCESS": 0,
	"LEAVE_GAME_FAIL":    1,
}

func (x LeaveGameResponCode) String() string {
	return proto.EnumName(LeaveGameResponCode_name, int32(x))
}
func (LeaveGameResponCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

// create room
type CreateRoomResponCode int32

const (
	CreateRoomResponCode_CREATE_ROOM_SUCCESS CreateRoomResponCode = 0
	CreateRoomResponCode_CREATE_ROOM_FAIL    CreateRoomResponCode = 1
)

var CreateRoomResponCode_name = map[int32]string{
	0: "CREATE_ROOM_SUCCESS",
	1: "CREATE_ROOM_FAIL",
}
var CreateRoomResponCode_value = map[string]int32{
	"CREATE_ROOM_SUCCESS": 0,
	"CREATE_ROOM_FAIL":    1,
}

func (x CreateRoomResponCode) String() string {
	return proto.EnumName(CreateRoomResponCode_name, int32(x))
}
func (CreateRoomResponCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type LoginReq struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *LoginReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type LoginRespon struct {
	Account    string          `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Token      string          `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	GateAddr   string          `protobuf:"bytes,3,opt,name=gate_addr,json=gateAddr" json:"gate_addr,omitempty"`
	ResponCode LoginResponCode `protobuf:"varint,4,opt,name=respon_code,json=responCode,enum=pb.LoginResponCode" json:"respon_code,omitempty"`
}

func (m *LoginRespon) Reset()                    { *m = LoginRespon{} }
func (m *LoginRespon) String() string            { return proto.CompactTextString(m) }
func (*LoginRespon) ProtoMessage()               {}
func (*LoginRespon) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *LoginRespon) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *LoginRespon) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRespon) GetGateAddr() string {
	if m != nil {
		return m.GateAddr
	}
	return ""
}

func (m *LoginRespon) GetResponCode() LoginResponCode {
	if m != nil {
		return m.ResponCode
	}
	return LoginResponCode_LOGIN_SUCCESS
}

type ConnectToGateReq struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Token   string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *ConnectToGateReq) Reset()                    { *m = ConnectToGateReq{} }
func (m *ConnectToGateReq) String() string            { return proto.CompactTextString(m) }
func (*ConnectToGateReq) ProtoMessage()               {}
func (*ConnectToGateReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ConnectToGateReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ConnectToGateReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ConnectToGateRespon struct {
	Account    string                  `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	ResponCode ConnectToGateResponCode `protobuf:"varint,2,opt,name=respon_code,json=responCode,enum=pb.ConnectToGateResponCode" json:"respon_code,omitempty"`
}

func (m *ConnectToGateRespon) Reset()                    { *m = ConnectToGateRespon{} }
func (m *ConnectToGateRespon) String() string            { return proto.CompactTextString(m) }
func (*ConnectToGateRespon) ProtoMessage()               {}
func (*ConnectToGateRespon) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ConnectToGateRespon) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *ConnectToGateRespon) GetResponCode() ConnectToGateResponCode {
	if m != nil {
		return m.ResponCode
	}
	return ConnectToGateResponCode_CONNECT_TO_GATE_SUCCESS
}

// get role list
type RoleInfo struct {
	PlayerId   uint32 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	PlayerName string `protobuf:"bytes,2,opt,name=player_name,json=playerName" json:"player_name,omitempty"`
}

func (m *RoleInfo) Reset()                    { *m = RoleInfo{} }
func (m *RoleInfo) String() string            { return proto.CompactTextString(m) }
func (*RoleInfo) ProtoMessage()               {}
func (*RoleInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *RoleInfo) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *RoleInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type RoleListReq struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *RoleListReq) Reset()                    { *m = RoleListReq{} }
func (m *RoleListReq) String() string            { return proto.CompactTextString(m) }
func (*RoleListReq) ProtoMessage()               {}
func (*RoleListReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *RoleListReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type RoleListRespon struct {
	Account  string      `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	RoleList []*RoleInfo `protobuf:"bytes,2,rep,name=role_list,json=roleList" json:"role_list,omitempty"`
}

func (m *RoleListRespon) Reset()                    { *m = RoleListRespon{} }
func (m *RoleListRespon) String() string            { return proto.CompactTextString(m) }
func (*RoleListRespon) ProtoMessage()               {}
func (*RoleListRespon) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *RoleListRespon) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *RoleListRespon) GetRoleList() []*RoleInfo {
	if m != nil {
		return m.RoleList
	}
	return nil
}

type CreateRoleReq struct {
	Account string `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
}

func (m *CreateRoleReq) Reset()                    { *m = CreateRoleReq{} }
func (m *CreateRoleReq) String() string            { return proto.CompactTextString(m) }
func (*CreateRoleReq) ProtoMessage()               {}
func (*CreateRoleReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *CreateRoleReq) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type CreateRoleRespon struct {
	Account    string               `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	ResponCode CreateRoleResponCode `protobuf:"varint,2,opt,name=respon_code,json=responCode,enum=pb.CreateRoleResponCode" json:"respon_code,omitempty"`
}

func (m *CreateRoleRespon) Reset()                    { *m = CreateRoleRespon{} }
func (m *CreateRoleRespon) String() string            { return proto.CompactTextString(m) }
func (*CreateRoleRespon) ProtoMessage()               {}
func (*CreateRoleRespon) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *CreateRoleRespon) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *CreateRoleRespon) GetResponCode() CreateRoleResponCode {
	if m != nil {
		return m.ResponCode
	}
	return CreateRoleResponCode_CREATE_ROLE_SUCCESS
}

type EnterGameReq struct {
	PlayerId uint32 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *EnterGameReq) Reset()                    { *m = EnterGameReq{} }
func (m *EnterGameReq) String() string            { return proto.CompactTextString(m) }
func (*EnterGameReq) ProtoMessage()               {}
func (*EnterGameReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *EnterGameReq) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type EnterGameRespon struct {
	PlayerId   uint32              `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	ResponCode EnterGameResponCode `protobuf:"varint,2,opt,name=respon_code,json=responCode,enum=pb.EnterGameResponCode" json:"respon_code,omitempty"`
}

func (m *EnterGameRespon) Reset()                    { *m = EnterGameRespon{} }
func (m *EnterGameRespon) String() string            { return proto.CompactTextString(m) }
func (*EnterGameRespon) ProtoMessage()               {}
func (*EnterGameRespon) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *EnterGameRespon) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *EnterGameRespon) GetResponCode() EnterGameResponCode {
	if m != nil {
		return m.ResponCode
	}
	return EnterGameResponCode_ENTER_GAME_SUCCESS
}

type LeaveGameReq struct {
	PlayerId uint32 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *LeaveGameReq) Reset()                    { *m = LeaveGameReq{} }
func (m *LeaveGameReq) String() string            { return proto.CompactTextString(m) }
func (*LeaveGameReq) ProtoMessage()               {}
func (*LeaveGameReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *LeaveGameReq) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type LeaveGameRespon struct {
	PlayerId   uint32              `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	ResponCode LeaveGameResponCode `protobuf:"varint,2,opt,name=respon_code,json=responCode,enum=pb.LeaveGameResponCode" json:"respon_code,omitempty"`
}

func (m *LeaveGameRespon) Reset()                    { *m = LeaveGameRespon{} }
func (m *LeaveGameRespon) String() string            { return proto.CompactTextString(m) }
func (*LeaveGameRespon) ProtoMessage()               {}
func (*LeaveGameRespon) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *LeaveGameRespon) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *LeaveGameRespon) GetResponCode() LeaveGameResponCode {
	if m != nil {
		return m.ResponCode
	}
	return LeaveGameResponCode_LEAVE_GAME_SUCCESS
}

type CreateRoomReq struct {
	PlayerId uint32 `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
}

func (m *CreateRoomReq) Reset()                    { *m = CreateRoomReq{} }
func (m *CreateRoomReq) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomReq) ProtoMessage()               {}
func (*CreateRoomReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *CreateRoomReq) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type CreateRoomRespon struct {
	PlayerId   uint32               `protobuf:"varint,1,opt,name=player_id,json=playerId" json:"player_id,omitempty"`
	RoomId     uint32               `protobuf:"varint,2,opt,name=room_id,json=roomId" json:"room_id,omitempty"`
	ResponCode CreateRoomResponCode `protobuf:"varint,3,opt,name=respon_code,json=responCode,enum=pb.CreateRoomResponCode" json:"respon_code,omitempty"`
}

func (m *CreateRoomRespon) Reset()                    { *m = CreateRoomRespon{} }
func (m *CreateRoomRespon) String() string            { return proto.CompactTextString(m) }
func (*CreateRoomRespon) ProtoMessage()               {}
func (*CreateRoomRespon) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *CreateRoomRespon) GetPlayerId() uint32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *CreateRoomRespon) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *CreateRoomRespon) GetResponCode() CreateRoomResponCode {
	if m != nil {
		return m.ResponCode
	}
	return CreateRoomResponCode_CREATE_ROOM_SUCCESS
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "pb.LoginReq")
	proto.RegisterType((*LoginRespon)(nil), "pb.LoginRespon")
	proto.RegisterType((*ConnectToGateReq)(nil), "pb.ConnectToGateReq")
	proto.RegisterType((*ConnectToGateRespon)(nil), "pb.ConnectToGateRespon")
	proto.RegisterType((*RoleInfo)(nil), "pb.RoleInfo")
	proto.RegisterType((*RoleListReq)(nil), "pb.RoleListReq")
	proto.RegisterType((*RoleListRespon)(nil), "pb.RoleListRespon")
	proto.RegisterType((*CreateRoleReq)(nil), "pb.CreateRoleReq")
	proto.RegisterType((*CreateRoleRespon)(nil), "pb.CreateRoleRespon")
	proto.RegisterType((*EnterGameReq)(nil), "pb.EnterGameReq")
	proto.RegisterType((*EnterGameRespon)(nil), "pb.EnterGameRespon")
	proto.RegisterType((*LeaveGameReq)(nil), "pb.LeaveGameReq")
	proto.RegisterType((*LeaveGameRespon)(nil), "pb.LeaveGameRespon")
	proto.RegisterType((*CreateRoomReq)(nil), "pb.CreateRoomReq")
	proto.RegisterType((*CreateRoomRespon)(nil), "pb.CreateRoomRespon")
	proto.RegisterEnum("pb.LoginResponCode", LoginResponCode_name, LoginResponCode_value)
	proto.RegisterEnum("pb.ConnectToGateResponCode", ConnectToGateResponCode_name, ConnectToGateResponCode_value)
	proto.RegisterEnum("pb.CreateRoleResponCode", CreateRoleResponCode_name, CreateRoleResponCode_value)
	proto.RegisterEnum("pb.EnterGameResponCode", EnterGameResponCode_name, EnterGameResponCode_value)
	proto.RegisterEnum("pb.LeaveGameResponCode", LeaveGameResponCode_name, LeaveGameResponCode_value)
	proto.RegisterEnum("pb.CreateRoomResponCode", CreateRoomResponCode_name, CreateRoomResponCode_value)
}

func init() { proto.RegisterFile("MsgDefine.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcf, 0x8f, 0xd2, 0x4e,
	0x14, 0xc0, 0xbf, 0x85, 0xaf, 0xbb, 0xf0, 0x58, 0x7e, 0x38, 0x10, 0x69, 0xc2, 0x41, 0xd2, 0x98,
	0xc8, 0xae, 0x86, 0xc3, 0xba, 0x07, 0x4d, 0xbc, 0xb0, 0x75, 0x44, 0x92, 0x42, 0x4d, 0x61, 0xbd,
	0x36, 0x85, 0xce, 0x22, 0x91, 0xce, 0xd4, 0xa1, 0x9a, 0x78, 0xf6, 0x1f, 0xf0, 0x4f, 0x36, 0x33,
	0x14, 0x99, 0x6d, 0x4b, 0x6b, 0xe2, 0x8d, 0x79, 0xef, 0xe5, 0x33, 0x9f, 0xf7, 0xde, 0x00, 0xd0,
	0x9c, 0xee, 0xd6, 0xef, 0xc8, 0xfd, 0x86, 0x92, 0x61, 0xc8, 0x59, 0xc4, 0x50, 0x29, 0x5c, 0x1a,
	0xcf, 0xa0, 0x62, 0xb1, 0xf5, 0x86, 0x3a, 0xe4, 0x2b, 0xd2, 0xe1, 0xdc, 0x5b, 0xad, 0xd8, 0x37,
	0x1a, 0xe9, 0x5a, 0x5f, 0x1b, 0x54, 0x9d, 0xc3, 0xd1, 0xf8, 0xa5, 0x41, 0x2d, 0x2e, 0xdb, 0x85,
	0x8c, 0x9e, 0xae, 0x44, 0x1d, 0x78, 0x14, 0xb1, 0x2f, 0x84, 0xea, 0x25, 0x19, 0xdf, 0x1f, 0x50,
	0x0f, 0xaa, 0x6b, 0x2f, 0x22, 0xae, 0xe7, 0xfb, 0x5c, 0x2f, 0xcb, 0x4c, 0x45, 0x04, 0x46, 0xbe,
	0xcf, 0xd1, 0x0d, 0xd4, 0xb8, 0xc4, 0xba, 0x2b, 0xe6, 0x13, 0xfd, 0xff, 0xbe, 0x36, 0x68, 0x5c,
	0xb7, 0x87, 0xe1, 0x72, 0xa8, 0x5c, 0x69, 0x32, 0x9f, 0x38, 0xc0, 0xff, 0x7c, 0x36, 0x6e, 0xa1,
	0x65, 0x32, 0x4a, 0xc9, 0x2a, 0x5a, 0xb0, 0xb1, 0x17, 0x91, 0xdc, 0x06, 0xb2, 0xb5, 0x8c, 0x00,
	0xda, 0x09, 0x46, 0x41, 0x77, 0x6f, 0x1f, 0xaa, 0x96, 0xa4, 0x6a, 0x4f, 0xa8, 0x66, 0x70, 0x52,
	0xca, 0x1f, 0xa0, 0xe2, 0xb0, 0x2d, 0x99, 0xd0, 0x7b, 0x26, 0x26, 0x12, 0x6e, 0xbd, 0x1f, 0x84,
	0xbb, 0x1b, 0x5f, 0xde, 0x52, 0x77, 0x2a, 0xfb, 0xc0, 0xc4, 0x47, 0x4f, 0xa1, 0x16, 0x27, 0xa9,
	0x17, 0x90, 0xd8, 0x19, 0xf6, 0xa1, 0x99, 0x17, 0x10, 0xe3, 0x39, 0xd4, 0x04, 0xc9, 0xda, 0xec,
	0xa2, 0xfc, 0xc5, 0xdd, 0x41, 0xe3, 0x58, 0x58, 0xd0, 0xdc, 0x25, 0x54, 0x39, 0xdb, 0x12, 0x77,
	0xbb, 0xd9, 0x45, 0x7a, 0xa9, 0x5f, 0x1e, 0xd4, 0xae, 0x2f, 0x44, 0x6b, 0x07, 0x67, 0xa7, 0xc2,
	0x63, 0x94, 0x71, 0x09, 0x75, 0x93, 0x13, 0xd1, 0x29, 0xdb, 0xe6, 0x4f, 0xde, 0x58, 0x43, 0x4b,
	0x2d, 0x2d, 0x70, 0x78, 0x93, 0x35, 0x60, 0x5d, 0x0e, 0x38, 0x01, 0x49, 0x4d, 0xf7, 0x05, 0x5c,
	0x60, 0x1a, 0x11, 0x3e, 0xf6, 0x02, 0xa9, 0x94, 0x37, 0x61, 0xe3, 0x33, 0x34, 0x95, 0x62, 0x29,
	0x95, 0xbb, 0x91, 0xd7, 0x59, 0x5e, 0x5d, 0xe1, 0x95, 0xc0, 0x64, 0x69, 0x59, 0xc4, 0xfb, 0x4e,
	0xfe, 0x56, 0x4b, 0x29, 0xfe, 0x17, 0xad, 0x04, 0x26, 0xa5, 0xf5, 0xf2, 0xb8, 0x41, 0x16, 0x14,
	0x7a, 0xfd, 0xd4, 0x8e, 0x5b, 0x14, 0xe5, 0xc5, 0x66, 0x5d, 0x38, 0xe7, 0x8c, 0x05, 0x22, 0x55,
	0x92, 0xa9, 0x33, 0x71, 0x9c, 0xf8, 0xc9, 0x0d, 0x97, 0xd3, 0x1b, 0x3e, 0x5c, 0x90, 0x74, 0xbe,
	0xba, 0x81, 0x66, 0xe2, 0x17, 0x01, 0x3d, 0x86, 0xba, 0x65, 0x8f, 0x27, 0x33, 0x77, 0x7e, 0x67,
	0x9a, 0x78, 0x3e, 0x6f, 0xfd, 0x87, 0x1a, 0x00, 0xfb, 0xd0, 0xfb, 0xd1, 0xc4, 0x6a, 0x69, 0x57,
	0x1f, 0xa1, 0x7b, 0xe2, 0xcb, 0x89, 0x7a, 0xd0, 0x35, 0xed, 0xd9, 0x0c, 0x9b, 0x0b, 0x77, 0x61,
	0xbb, 0xe3, 0xd1, 0x02, 0x2b, 0x1c, 0x1d, 0x3a, 0xc9, 0x64, 0x4c, 0xc4, 0xd0, 0xc9, 0x7a, 0x8d,
	0xa8, 0x0b, 0x6d, 0xd3, 0xc1, 0xa2, 0xd0, 0xb1, 0x2d, 0x15, 0xd5, 0x81, 0x96, 0x9a, 0x88, 0x31,
	0xb7, 0xd0, 0xce, 0x78, 0x3c, 0xe8, 0x09, 0x20, 0x3c, 0x5b, 0x60, 0xc7, 0x1d, 0x8f, 0xa6, 0x2a,
	0xa4, 0x0d, 0x4d, 0x25, 0x7e, 0x64, 0x64, 0x6c, 0x5a, 0x30, 0x2c, 0x3c, 0xfa, 0x84, 0x33, 0x18,
	0x4a, 0x3c, 0xdd, 0x8e, 0x3a, 0xfa, 0x07, 0xed, 0xd8, 0xd3, 0x13, 0xed, 0xd8, 0xd3, 0x18, 0xb3,
	0x3c, 0x93, 0x7f, 0x2a, 0xaf, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x25, 0x70, 0x3e, 0x67,
	0x06, 0x00, 0x00,
}
